# Generated by Django 4.2.2 on 2023-06-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected')], max_length=1, null=True),
        ),
    ]
