# Generated by Django 4.2.2 on 2023-06-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poster', '0002_alter_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected')], max_length=1, null=True),
        ),
    ]
